In [4]:
import numpy as np
array1=np.array([[1,2,2,3,4],[1,28,2,6,8]],dtype='int32')
print(array1)
print(array1.shape)
print(array1.dtype)

[[ 1  2  2  3  4]
 [ 1 28  2  6  8]]
(2, 5)
int32


In [5]:
print(np.ones((4,6)))
print(np.ones((4,6)).dtype)
print(np.empty((4,6))) # it will return a memory to array it will not always zero it will be random

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
float64
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [6]:
print(array1,'\n')
print(array1*array1,,'\n') # element wise multiplication
print(array1**array1) # element wise multiplication

SyntaxError: invalid syntax (589181609.py, line 2)

In [ ]:
array2=np.array([5,4,64,3,3,3])
arr=array2[4:6]
arr[0]=9 # it will change the value of the array2 as well if you not want this then please copy the array2
print(array2,'see this is changed')
array2=np.array([5,4,64,3,3,3]) # reassigning the array2
arr=array2[4:6].copy() # it will not change the value of the array2
arr[0]=9 # it will not change the value of the array2
print(array2,'see this is not changed')


[ 5  4 64  3  9  3] see this is changed
[ 5  4 64  3  3  3] see this is not changed


In [ ]:
ar1=np.array([[1,2,3],[4,5,6]])
print(ar1.sum(axis=1)) # it will return the sum of each row
print(ar1.sum(axis=0)) # it will return the sum of each column
ar2=np.array([[4,5,6],[7,8,9]])
np.dot(ar1,ar2.transpose()) # it will return the dot product of the two matrix
np.cross(ar1,ar2) # it will return the cross product of the two matrix

[ 6 15]
[5 7 9]


array([[-3,  6, -3],
       [-3,  6, -3]])

In [8]:
a=np.array([[89,2,63],[25,6,4]])
print(np.sort(a)) # it will return the sorted array
print("")
print(np.sort(a,axis=0)) # it will return the sorted array along the column
print("")
print(np.sort(a,axis=0,kind='mergesort')) # it will return the sorted array along the column by merge sort


[[ 2 63 89]
 [ 4  6 25]]

[[25  2  4]
 [89  6 63]]

[[25  2  4]
 [89  6 63]]


In [16]:
b=np.array([1,25,25,64,4,5004,54,5,4,967,84,54,3,5,9,4,8,9,7,25,1])
print(b.shape,'\n')
print(b.reshape(7,3),'\n') # it will return the array in the shape of 7*3 matrix
print(np.argsort(b),'\n') # it will return position of the sortation element array
print(np.argmin(b),'\n') # it will return the position of the minimum element
print(np.argmax(b),'\n') # it will return the position of the maximum element

(21,) 

[[   1   25   25]
 [  64    4 5004]
 [  54    5    4]
 [ 967   84   54]
 [   3    5    9]
 [   4    8    9]
 [   7   25    1]] 

[ 0 20 12  4  8 15  7 13 18 16 17 14  2 19  1 11  6  3 10  9  5] 

0 

5 

